spring:
  datasource:
    url: jdbc:mysql://localhost:3306/segaedu?createDatabaseIfNotExist=true
    username: root
    password: system
    testWhileIdle: true
    validationQuery: SELECT 1
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
      naming-strategy: org.hibernate.cfg.ImprovedNamingStrategy
      dialect: org.hibernate.dialect.MySQL5Dialect


#security:
#  user:
#    name: ashmeet
#    password: tiwary
#    role: ADMIN

#    name: admin
#    password: admin
#    role: ADMIN
